platform :ios, "8.0"

target 'MBBook' do
inhibit_all_warnings!

# funcs
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'YYCache'
    pod 'YYModel'
    pod 'YYCategories'
    pod 'MJRefresh'
    pod 'MBProgressHUD'

# data analysis
    pod 'UMengAnalytics'

end
